{% set name = "unittest2pytest" %}
{% set version = "0.5" %}
{% set hash = "245db168f4286470ffc932b8d055cd0062ff26dfe2c8138ba8cc93672bb520f4" %}
{% set ext = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ ext }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext }}
  sha256: {{ hash }}

build:
  number: 0
  script: script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - unittest2pytest = unittest2pytest.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - unittest2pytest --help

about:
  home: https://github.com/pytest-dev/unittest2pytest
  license: GPL-3.0
  license_file: COPYING-GPLv3.txt
  summary: unittest2pytest is a tool that helps rewriting Python unittest test-cases into pytest test-cases.

extra:
  recipe-maintainers:
    - nicoddemus
    - gqmelo
