travis:
  secure:
    BINSTAR_TOKEN: XKeKG+I0Yc3N9jsgUby1uxwAsEEK636YTmaDJ54C/3B6vxSDZt1yMR6JuYp2mcqA2IMeOOxgSzGSNEXmfOx9Wzw5xXVzhTYSiaLvwhgtKL45ZZz+gYWFro13b+HzjU8VaMyU7mlpOXpmUnbOzbojZ6TDRTLnSsLQCFrUdZm3x4LL3s169r/TRV4FteIZCIcDQJLN/mclXWfh9Wc8dGFUDyN7SROnnW/gXFpea6JCk6YTRQoDz4+Rf8B//IYqMHAETRHQbJ+Bz5hH0j6/VFKCFYuG+gMtD3srxnqu49Lb6iSlcfb+wgO+h+pGM374m/z6Xj2UdFQSPh2yAOcLeV+hHIezOrKCb/JuCVXJodr21bKz5+pMyOKqI5Eaw7+Q4huvs4V7RP6maQcbSvauoylfqJ9yapZNnZCTB+XSgnu09PGo/07HPBQucPzhtCbMTt+ZsZRESwm2kGuPW7Pgi/BsPZEvyn3kj+gHmDLPNOxcPT6LA688sh8OQBGJEpaiUNQztXX80VfsVckZjqpj/HnxoxtpoVw3+kS3XSVKxSeCMBQbypYI2zd6iP8gTLnUYelgO+v14L2CcivK//ZdH6HVEkckV/yQ+1oqFfNpZt8Pqwmw7bnpCbbjuAH+yo3STyy7YINIA/cmYVI7DDl51ckfr42SZVx/03rWxXeJib4gv/I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
